apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    metadata:
      name: helloworld-go-v2
    spec:
      containers:
        - image: asia.gcr.io/my-knative-project-101/hello-world-knative:latest
          env:
            - name: TARGET
              value: "v2"
  traffic:
  - tag: stable
    revisionName: helloworld-go-v1
    percent: 70
  - tag: candidate
    revisionName: helloworld-go-v2
    percent: 30