apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: ui
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: asia.gcr.io/my-knative-project-101/ui-angular