apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: message-service-nodejs
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: asia.gcr.io/my-knative-project-101/message-service-nodejs
        env:
        - name: TARGET
          value: "Node.js Sample v1"
