apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: message-sentiment-analyser
spec:
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: sentiment-analysis-service